### ISSUE TITLE
Thảo luận về nội dung 2 tuần học tiếp theo.

### ISSUE THREAD

**Issue by tpphu** [tpphu/golang-training#15]
Chúng ta đã trải qua xem như 3 tuần về các chủ đề khác nhau

1. Học về ngôn ngữ, viết mấy cái helpers function
2. Học về crawler, để biết cách viết một cái job, backend hay viết job để xử lý các bài toán dạng như vậy
3. Học về viết RestAPI
Thiết kế chương trình sẽ còn 2 tuần nữa
Sẽ tập trung giúp các bạn tư duy và hoàn thiện chương trình, deployment, testing, v.v...
Và giúp các bạn làm một bài tập cuối cùng (final project)
Tuy nhiên Phú nghĩ sẽ là thiếu sót nếu không dạy cho các bạn thêm một số khái niệm về microservices, với grpc, service discovery
Nhưng vì còn 2 tuần nếu dạy cho các bạn cái này, sẽ là một lượng kiến thức không nhỏ, mà nếu các bạn không tự học thêm thì sẽ không vượt qua được.
Nên Phú vẫn đang rất phân vân, không biết phải xử lý tình huống này như thế nào
Bởi có một vài bạn trong lớp thì chịu học và làm bài tập, vượt khó để làm ở nhà, một vài bạn thì lại không có thời gian.
Các bạn cho ý kiến nha.
A) Hoàn thiện kiến thức lại ở những điểm mà mọi người chưa hiểu trong 3 tuần qua, và giúp mọi người làm final project của mình
B) Tiếp tục học về microservices, grpc, service discovery
Tất nhiên các bạn vẫn phải viết unit testing, làm CI/CD v.v.. :smile:
Nói chung kiến thức 3 tuần qua Phú nghĩ là cũng khá kute, giúp các bạn từ đó tư duy tiếp, vì thường backend chỉ có 3 bài toán cơ bản đó :smile:
Giờ thì thế giới thay đổi zồi, nên sẽ phức tạp hơn chút xíu ở một vài khía cạnh khác
Các bạn si nghĩ, thật nghiêm túc nha, rồi trả lời mình
Thường các bạn hào hứng cái gì cũng thích học mà hem có thích làm :smile:

**Comment by hiepndd** [comment]
Da em chon phuong an B nha anh @tpphu

**Comment by lyquocnam** [comment]
Em cũng chọn phương án B :)
