### ISSUE TITLE
Nhờ xây dựng danh sách về tools, resource, link hay để chia sẽ cho nhau

### ISSUE THREAD

**Issue by tpphu** [tpphu/golang-training#7]
Hi các bạn,

Mình nghĩ ai trong chúng ta trong quãng đường đi code cũng có không ít điều hay muốn chia sẽ:

1. Về công cụ lập trình, tools
2. Về các resource hay như ebook, khóa học v.v...
3. Về cá link hay cần đọc.

Nên mình tạo ra thread này để chúng ta cùng chia sẽ với nhau nha.

Cảm ơn các bạn.

**Comment by tpphu** [comment]
Tool đầu tiên mình muốn chia sẽ là tool này, thay cho Postman

https://insomnia.rest/

Lý do mình dùng tool này là khi mình dùng ES, ES thiết kế phương thức GET như có Body là JSON, mà Postman thì nó không cho.

Mình thấy tool này rất hay, cho phép cài cắm plugin và có nhiều cái như suggestion rất tiện.
Chưa kể nó opensource, các bạn thấy thích có thể tự build và thêm chức năng cho mình.

**Comment by mrthanduc** [comment]
A curated list of awesome Go frameworks, libraries and software 
https://awesome-go.com/
https://github.com/avelino/awesome-go

**Comment by tpphu** [comment]
Một công cụ test tuyệt vời dành cho Go

http://goconvey.co/

**Comment by tpphu** [comment]
Một công cụ về mặt Todo ở dạng terminal rất hay

https://github.com/klaussinani/taskbook
